### ISSUE TITLE
Add RDAP server URLs

### ISSUE THREAD

**Issue by case** [zonedb/zonedb#828]
Data source, for gTLDs (and a few ccTLDs): https://data.iana.org/rdap/dns.json

We'd need to manually add ccTLD hosts as we find them, for example:

- [x] .li: `https://rdap.nic.li/domain/apple.li`
- [x] .ch: `https://rdap.nic.ch/domain/apple.ch`
    - Docs: https://www.nic.li/whois/rdap/
- [x] .de: `https://rdap.denic.de/domain/apple.de`
    - Docs: https://www.denic.de/en/rdap/
- [x] CentralNic SLDs: "Unfortunately, since the IANA can only accept registrations for top-level domains, CentralNic's SLD portfolio cannot be added to the registry. However, the RDAP service is available for these domains, at `https://rdap.centralnic.com/{sld}`"
    - Docs: https://centralnicregistry.com/support/information/rdap

CentralNic SLDs:

- [x] ae.org
- [x] br.com
- [x] cn.com
- [x] co.com
- [x] co.nl
- [x] co.no
- [x] com.de
- [x] com.se
- [x] de.com
- [x] eu.com
- [x] gb.net
- [x] gr.com
- [x] hu.net
- [x] in.net
- [x] jp.net
- [x] jpn.com
- [x] mex.com
- [x] radio.am
- [x] radio.fm
- [x] ru.com
- [x] sa.com
- [x] se.net
- [x] uk.com
- [x] uk.net
- [x] us.com
- [x] us.org
- [x] za.com

These ccTLDs are already in the IANA file:

```
ca
fo
gd
pw
vg
is
ar
cr
cz
no
id
br
cc
tv
ky
tz
```

**Comment by chriskillpack** [comment]
The `dns.json` schema allows multiple RDAP endpoints per zone / TLD, yet the file only lists a single RDAP endpoint. Do we have documentation on the schema or whether this is intentional? We can propagate support for multiple RDAP endpoints into the ZoneDB schema but I want to understand if support is necessary.

**Comment by case** [comment]
This is 99% done; I still need to manually add a few which weren't in the IANA file.

**Comment by case** [comment]
This is done.
